### ISSUE TITLE
[BUG] Page incomplete

### ISSUE THREAD

**Issue by ozmule** [HCL-TECH-SOFTWARE/domino-keep-tutorials#20]
**Type**
[ ] Typo
[X] Broken Link
[ ] Inaccurate
[X] Incomplete

**Describe the error**
Page in documentation missing.

**Page**
https://opensource.hcltechsw.com/Domino-rest-api/installconfig/configuration/security/authentication

**To Reproduce**
1. Go to page https://opensource.hcltechsw.com/Domino-rest-api/installconfig/installation/postinstallation.html
2. Scroll down to heading Configure JWT
3. Click heading "Configure JWT"

**Expected behavior**
New page should be loaded. Currently getting 404 error

**Screenshots**
<img width="365" alt="image" src="https://user-images.githubusercontent.com/63888591/214763211-aae47942-5bda-4f5e-a122-e30ab97e20d8.png">

**Comment by paulswithers** [comment]
Issue raised on Domino REST API documentation, https://github.com/HCL-TECH-SOFTWARE/Domino-rest-api/issues/3
